//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetWeatherInfoFromJMA.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesActivities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesActivities() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GetWeatherInfoFromJMA.Activities.Properties.ResourcesActivities", typeof(ResourcesActivities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Eq Vol Feed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EqVolFeed {
            get {
                return ResourceManager.GetString("EqVolFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extra Feed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExtraFeed {
            get {
                return ResourceManager.GetString("ExtraFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GetAtomFeed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetAtomFeedDescription {
            get {
                return ResourceManager.GetString("GetAtomFeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GetAtomFeed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetAtomFeedDisplayName {
            get {
                return ResourceManager.GetString("GetAtomFeedDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetAtomFeedResultDescription {
            get {
                return ResourceManager.GetString("GetAtomFeedResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetAtomFeedResultDisplayName {
            get {
                return ResourceManager.GetString("GetAtomFeedResultDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetForecastAreaDescription {
            get {
                return ResourceManager.GetString("GetForecastAreaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetForecastAreaDisplayName {
            get {
                return ResourceManager.GetString("GetForecastAreaDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GetWeatherForecast に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetForecastDescription {
            get {
                return ResourceManager.GetString("GetForecastDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GetForecast に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetForecastDisplayName {
            get {
                return ResourceManager.GetString("GetForecastDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetForecastResultDescription {
            get {
                return ResourceManager.GetString("GetForecastResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetForecastResultDisplayName {
            get {
                return ResourceManager.GetString("GetForecastResultDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get Typhoon Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetTyphoonInfoDescription {
            get {
                return ResourceManager.GetString("GetTyphoonInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GetTyphoonInfo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetTyphoonInfoDisplayName {
            get {
                return ResourceManager.GetString("GetTyphoonInfoDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID list to be ignored に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetTyphoonInfoIgnoreIdListDescription {
            get {
                return ResourceManager.GetString("GetTyphoonInfoIgnoreIdListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IgnoreIdList に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetTyphoonInfoIgnoreIdListDisplayName {
            get {
                return ResourceManager.GetString("GetTyphoonInfoIgnoreIdListDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Typhoon number list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetTyphoonInfoNumberListDescription {
            get {
                return ResourceManager.GetString("GetTyphoonInfoNumberListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NumberList に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetTyphoonInfoNumberListDisplayName {
            get {
                return ResourceManager.GetString("GetTyphoonInfoNumberListDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProcessedIdList に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetTyphoonInfoProcessedIdListDescription {
            get {
                return ResourceManager.GetString("GetTyphoonInfoProcessedIdListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProcessedIdList に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetTyphoonInfoProcessedIdListDisplayName {
            get {
                return ResourceManager.GetString("GetTyphoonInfoProcessedIdListDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetTyphoonInfoResultDescription {
            get {
                return ResourceManager.GetString("GetTyphoonInfoResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetTyphoonInfoResultDisplayName {
            get {
                return ResourceManager.GetString("GetTyphoonInfoResultDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area which you want to get warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetWarningAreaDescription {
            get {
                return ResourceManager.GetString("GetWarningAreaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetWarningAreaDisplayName {
            get {
                return ResourceManager.GetString("GetWarningAreaDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get Warning in WeatherInfoScope に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetWarningDescription {
            get {
                return ResourceManager.GetString("GetWarningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetWarningDisplayName {
            get {
                return ResourceManager.GetString("GetWarningDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID list to be ignored に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetWarningIgnoreIdListDescription {
            get {
                return ResourceManager.GetString("GetWarningIgnoreIdListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IgnoreIdList に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetWarningIgnoreIdListDisplayName {
            get {
                return ResourceManager.GetString("GetWarningIgnoreIdListDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Separator b/w large area and small area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetWarningKeyNameSeparatorDescription {
            get {
                return ResourceManager.GetString("GetWarningKeyNameSeparatorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KeyNameSeparator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetWarningKeyNameSeparatorDisplayName {
            get {
                return ResourceManager.GetString("GetWarningKeyNameSeparatorDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IDs which have been processed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetWarningProcessedIdListDescription {
            get {
                return ResourceManager.GetString("GetWarningProcessedIdListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processed ID List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetWarningProcessedIdListDisplayName {
            get {
                return ResourceManager.GetString("GetWarningProcessedIdListDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetWarningResultDescription {
            get {
                return ResourceManager.GetString("GetWarningResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetWarningResultDisplayName {
            get {
                return ResourceManager.GetString("GetWarningResultDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AtomFeedType に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetXmlAtomFeedTypeDescription {
            get {
                return ResourceManager.GetString("GetXmlAtomFeedTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AtomFeedType に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetXmlAtomFeedTypeDisplayName {
            get {
                return ResourceManager.GetString("GetXmlAtomFeedTypeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get specific XML  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetXmlDescription {
            get {
                return ResourceManager.GetString("GetXmlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get XML に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetXmlDisplayName {
            get {
                return ResourceManager.GetString("GetXmlDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InformationName (Should be Japanese) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetXmlInformationNameDescription {
            get {
                return ResourceManager.GetString("GetXmlInformationNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InformationName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetXmlInformationNameDisplayName {
            get {
                return ResourceManager.GetString("GetXmlInformationNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MeteorologicalOfficeName (Should be Japanese) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetXmlMeteorologicalOfficeDescription {
            get {
                return ResourceManager.GetString("GetXmlMeteorologicalOfficeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MeteorologicalOfficeName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetXmlMeteorologicalOfficeName {
            get {
                return ResourceManager.GetString("GetXmlMeteorologicalOfficeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetXmlResultDescription {
            get {
                return ResourceManager.GetString("GetXmlResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetXmlResultDisplayName {
            get {
                return ResourceManager.GetString("GetXmlResultDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return All Matches に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetXmlReturnAllMatchesDescription {
            get {
                return ResourceManager.GetString("GetXmlReturnAllMatchesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return All Matches に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetXmlReturnAllMatchesDisplayName {
            get {
                return ResourceManager.GetString("GetXmlReturnAllMatchesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide a value for {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetadataValidationError {
            get {
                return ResourceManager.GetString("MetadataValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other Feed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OtherFeed {
            get {
                return ResourceManager.GetString("OtherFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regular Feed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegularFeed {
            get {
                return ResourceManager.GetString("RegularFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.data.jma.go.jp/developer/xml/feed/eqvol.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlDefaultHighFreqEqVol {
            get {
                return ResourceManager.GetString("UrlDefaultHighFreqEqVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.data.jma.go.jp/developer/xml/feed/extra.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlDefaultHighFreqExtra {
            get {
                return ResourceManager.GetString("UrlDefaultHighFreqExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.data.jma.go.jp/developer/xml/feed/other.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlDefaultHighFreqOther {
            get {
                return ResourceManager.GetString("UrlDefaultHighFreqOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.data.jma.go.jp/developer/xml/feed/regular.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlDefaultHighFreqRegular {
            get {
                return ResourceManager.GetString("UrlDefaultHighFreqRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.data.jma.go.jp/developer/xml/feed/eqvol_l.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlDefaultLongTermEqVol {
            get {
                return ResourceManager.GetString("UrlDefaultLongTermEqVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.data.jma.go.jp/developer/xml/feed/extra_l.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlDefaultLongTermExtra {
            get {
                return ResourceManager.GetString("UrlDefaultLongTermExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.data.jma.go.jp/developer/xml/feed/other_l.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlDefaultLongTermOther {
            get {
                return ResourceManager.GetString("UrlDefaultLongTermOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.data.jma.go.jp/developer/xml/feed/regular_l.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlDefaultLongTermRegular {
            get {
                return ResourceManager.GetString("UrlDefaultLongTermRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Default High Freq Earthquake Volcano に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeDefaultHighFreqEqVolDescription {
            get {
                return ResourceManager.GetString("WeatherInfoScopeDefaultHighFreqEqVolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default High Freq に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeDefaultHighFreqEqVolDisplayName {
            get {
                return ResourceManager.GetString("WeatherInfoScopeDefaultHighFreqEqVolDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Default High Freq As Needed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeDefaultHighFreqExtraDescription {
            get {
                return ResourceManager.GetString("WeatherInfoScopeDefaultHighFreqExtraDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default High Freq に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeDefaultHighFreqExtraDisplayName {
            get {
                return ResourceManager.GetString("WeatherInfoScopeDefaultHighFreqExtraDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Default High Freq Other に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeDefaultHighFreqOtherDescription {
            get {
                return ResourceManager.GetString("WeatherInfoScopeDefaultHighFreqOtherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default High Freq に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeDefaultHighFreqOtherDisplayName {
            get {
                return ResourceManager.GetString("WeatherInfoScopeDefaultHighFreqOtherDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Default High Freq Periodic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeDefaultHighFreqRegularDescription {
            get {
                return ResourceManager.GetString("WeatherInfoScopeDefaultHighFreqRegularDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default High Freq に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeDefaultHighFreqRegularDisplayName {
            get {
                return ResourceManager.GetString("WeatherInfoScopeDefaultHighFreqRegularDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Default Long Term に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeDefaultLongTermEqVolDescription {
            get {
                return ResourceManager.GetString("WeatherInfoScopeDefaultLongTermEqVolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default Long Term に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeDefaultLongTermEqVolDisplayName {
            get {
                return ResourceManager.GetString("WeatherInfoScopeDefaultLongTermEqVolDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Default Long Term に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeDefaultLongTermExtraDescription {
            get {
                return ResourceManager.GetString("WeatherInfoScopeDefaultLongTermExtraDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default Long Term に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeDefaultLongTermExtraDisplayName {
            get {
                return ResourceManager.GetString("WeatherInfoScopeDefaultLongTermExtraDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Default Long Term に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeDefaultLongTermOtherDescription {
            get {
                return ResourceManager.GetString("WeatherInfoScopeDefaultLongTermOtherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default Long Term に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeDefaultLongTermOtherDisplayName {
            get {
                return ResourceManager.GetString("WeatherInfoScopeDefaultLongTermOtherDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Default Long Term に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeDefaultLongTermPeriodicDescription {
            get {
                return ResourceManager.GetString("WeatherInfoScopeDefaultLongTermPeriodicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default Long Term に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeDefaultLongTermPeriodicDisplayName {
            get {
                return ResourceManager.GetString("WeatherInfoScopeDefaultLongTermPeriodicDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The scope is for obtaining Weather Info XML from JMA に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeDescription {
            get {
                return ResourceManager.GetString("WeatherInfoScopeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weather Info Scope に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeDisplayName {
            get {
                return ResourceManager.GetString("WeatherInfoScopeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output Feeds as Dictionary type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeOutputDescription {
            get {
                return ResourceManager.GetString("WeatherInfoScopeOutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output Feeds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeOutputDisplayName {
            get {
                return ResourceManager.GetString("WeatherInfoScopeOutputDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL or Filepath for Earthquake Volcano Feed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeURLEqVolDescription {
            get {
                return ResourceManager.GetString("WeatherInfoScopeURLEqVolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL EqVc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeURLEqVolDisplayName {
            get {
                return ResourceManager.GetString("WeatherInfoScopeURLEqVolDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL or Filepath for As Needed Feed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeURLExtraDescription {
            get {
                return ResourceManager.GetString("WeatherInfoScopeURLExtraDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL Extra に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeURLExtraDisplayName {
            get {
                return ResourceManager.GetString("WeatherInfoScopeURLExtraDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL or Filepath for Other Feed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeURLOtherDescription {
            get {
                return ResourceManager.GetString("WeatherInfoScopeURLOtherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL Other に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeURLOtherDisplayName {
            get {
                return ResourceManager.GetString("WeatherInfoScopeURLOtherDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL or Filepath for Preodic Feed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeURLRegularDescription {
            get {
                return ResourceManager.GetString("WeatherInfoScopeURLRegularDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL Regular に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WeatherInfoScopeURLRegularDisplayName {
            get {
                return ResourceManager.GetString("WeatherInfoScopeURLRegularDisplayName", resourceCulture);
            }
        }
    }
}
