//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetWeatherInfoFromJMA {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GetWeatherInfoFromJMA.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EqVol.
        /// </summary>
        public static string EQVOL {
            get {
                return ResourceManager.GetString("EQVOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        public static string EXTRA {
            get {
                return ResourceManager.GetString("EXTRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 府県天気予報.
        /// </summary>
        public static string FORECAST_TITLE {
            get {
                return ResourceManager.GetString("FORECAST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetForecast.
        /// </summary>
        public static string GetForecast {
            get {
                return ResourceManager.GetString("GetForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetTyphoonInfo.
        /// </summary>
        public static string GetTyphoonInfo {
            get {
                return ResourceManager.GetString("GetTyphoonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetWarning.
        /// </summary>
        public static string GetWarning {
            get {
                return ResourceManager.GetString("GetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OTHER {
            get {
                return ResourceManager.GetString("OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        public static string REGULAR {
            get {
                return ResourceManager.GetString("REGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全般台風情報（定型）.
        /// </summary>
        public static string TYPHOON_TITLE {
            get {
                return ResourceManager.GetString("TYPHOON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60.
        /// </summary>
        public static string WaitTimeSec {
            get {
                return ResourceManager.GetString("WaitTimeSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 気象特別警報・警報・注意報.
        /// </summary>
        public static string WARNING_TITLE {
            get {
                return ResourceManager.GetString("WARNING_TITLE", resourceCulture);
            }
        }
    }
}
